### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by nicholastillman** [minamarkham/sassy-starter#5]
looks like the build failed on me. Also gulp command not working. Kind of new to OSX environment, been on windows past years, any tips?

**Comment by max1011** [comment]
@tillfour talking generally (not much related to this specific issue) , learn linux => ubuntu / OSX or any other linux distribution , in that environment you have first to learn how to use the command line (CLI) and then learn gulp and what's related to it.

**Comment by minamarkham** [comment]
@tillfour try installing gulp using `npm install gulp -g`

**Comment by minamarkham** [comment]
Fixed with 65b2fa846aa21dfe8dd5334c43230ad247bb77e5
