### ISSUE TITLE
"Error: libsass bindings not found. Try reinstalling node-sass?"

### ISSUE THREAD

**Issue by jpwitkowski11** [minamarkham/sassy-starter#7]
First of all, thank you! Awesome starter kit! Love it!

I ran into this issue: after `npm install` I ran `gulp` but kept getting the following message:
`Error: libsass bindings not found. Try reinstalling node-sass?`

I ran `npm install gulp-sass@latest` and then re-ran `gulp` and that resolved the issue.
I'm running node v5.9.1, npm v3.8.5. 

thanks again!

**Comment by keoshi** [comment]
@jwitkowski try running these two commands:

```
npm uninstall --save-dev gulp-sass

npm install --save-dev gulp-sass@2
```

**Comment by minamarkham** [comment]
This should be fixed in the latest version.

**Comment by jpwitkowski11** [comment]
Ty!
